apps:
  - name: hawkins
    script: ./index.js
    exec_mode: cluster
    instances: 2
    watch: false
    max_memory_restart: 200M
  - name: upside-down
    script: ./index.js
    exec_mode: cluster
    instances: 2
    watch: false
    max_memory_restart: 200M