apps:

- name: fernanda-bk
  script: ./index.js
  exec_mode: cluster
  instances: 2
  max_memory_restart: 200M
- name: fernanda-bk
  script: ./index.js
  exec_mode: cluster
  instances: 2
  max_memory_restart: 200M